### ISSUE TITLE
Gerando Artigo Científico no Windows 10

### ISSUE THREAD

**Issue by vitorcalvi** [bcdavasconcelos/ABNTeX-o-matic#1]
Ola Bernardo, como vai?! Achei muito direto e pratico o seu repositório. Estou buscando uma solução para meus TCCs. Vamos lá. 

Consegui gerar o artigo científico no Sistema Operacional Windows 10 porém, a capa não saiu.
Você poderia me ajudar nisso. Estou usando o pandoc 2.14

Abraços!

**Comment by bcdavasconcelos** [comment]
Salve @vitorcalvi, tranquilo?

A capa só é gerada se alguns itens de metadados estiverem preenchidos. São eles: `titulo`, `instituicao`, `ano`, `lugar`. Como você está fazendo um TCC, então você precisa passar também o item `contracapa` para ter aquela descrição da contra-capa:

`TCC apresentada ao programa ...da ..., como requisito parcial para a obtenção do título de ...`

Vê se consegue. Caso não consiga, posta o seu cabeçalho YAML e eu te ajudo a fazer o debug.

Abraço!

**Comment by vitorcalvi** [comment]
Bacana @bcdavasconcelos muito obrigado! Sim gerou perfeitamente com suas orientações. Parabéns. 
Vamos lá, por favor, se você puder me ajudar. Tenho 3 TCCs (1 Dissertação e 2 Relatórios técnicos) pra fazer. Então, a sua solução é ideal para mim. :)))

Se não estou enganado, há algumas modificações como citações e outros que ainda não sei. Creio que a tipografia não é Arial 12.

Qual orientação você poderia me dar para eu formatar no padrão ABNT e extender a sua solução. Faria um Fork. Bom que ajudará outros colegas também. 

Abraços! Buongiorno

**Comment by bcdavasconcelos** [comment]
Salve Vitor,

não teria nenhuma orientação, pois a formatação está de acordo com a ABNT. Até onde eu sei a ABNT não especifica fonte (apesar de alguns departamentos pedirem arial ou times new roman). Se quiser mudar, basta passar o parâmetro fonte no cabeçalho YAML, [conforme instruções](https://github.com/bcdavasconcelos/ABNTeX-o-matic#funcionamento-do-template).

Qualquer outra dúvida, é só dizer.

Abraço!
Bernardo
